// resources/js/pages/Kepengurusan/Kominfo.tsx
import KepengurusanCard from '@/components/core-card-kepengurusan';
import Heading from '@/components/core-heading';
import KepengurusanHeading from '@/components/core-heading-kepengurusan';
import { kepengurusan } from '@/constants/kepengurusan/kominfo';
import { Head } from '@inertiajs/react';
import MainLayout from '../Layout';

export default function Kominfo() {
    return (
        <>
            <Head title="Kominfo Kami" />
            <MainLayout>
                <Heading img="/images/100101.png" />
                <section className="pt-20 pb-10 lg:pt-[120px] lg:pb-20">
                    <div className="container mx-auto">
                        <KepengurusanHeading jobdesk="Kominfo Kami" />
                        <div className="mx-4 flex flex-wrap justify-center gap-20">
                            {kepengurusan.map((pengurus) => (
                                <KepengurusanCard key={pengurus.id} pengurus={pengurus} />
                            ))}
                        </div>
                    </div>
                </section>
            </MainLayout>
        </>
    );
}

// resources/js/Pages/Kepengurusan/Kominfo.vue
<template>

  <Loading v-if="isLoading" />

  <Head title="Kominfo COMIT">
    <link rel="icon" href="/images/logo_black.png" />
    <meta name="description" content="Kepengurusan COMIT 2024-2025 (Sahitya Arsa).">
  </Head>

  <Main :user="props.user">
    <Heading img="/images/100101.png" />
    <section class="pt-20 lg:pt-[120px] pb-10 lg:pb-20">
      <div class="container mx-auto">
        <KepengurusanHeading jobdesk="Kominfo Kami" />
        <div class="flex flex-wrap gap-20 justify-center mx-4">
          <KepengurusanCard v-for="pengurus in kepengurusan" :key="pengurus.id" :pengurus="pengurus" />
        </div>
      </div>
    </section>
  </Main>
</template>

<script setup>
import Main from '@/Layouts/Main.vue';
import Loading from '@/components/Loading.vue';
import Heading from '@/components/ui/Heading.vue';
import KepengurusanCard from '@/components/ui/KepengurusanCard.vue';
import KepengurusanHeading from '@/components/ui/KepengurusanHeading.vue';

import { Head } from '@inertiajs/vue3';
import { useLoading } from '@/hooks/useLoading';
import { kepengurusan } from '@/data/kepengurusan/kominfo.js';

const { isLoading } = useLoading();

const props = defineProps({
  user: Object,
});
</script>
