// resources/js/pages/Kepengurusan/Sekretaris.tsx
import KepengurusanCard from '@/components/core-card-kepengurusan';
import Heading from '@/components/core-heading';
import KepengurusanHeading from '@/components/core-heading-kepengurusan';
import { kepengurusan } from '@/constants/kepengurusan/sekretaris';
import MainLayout from '@/layouts/main-layout';
import { Head } from '@inertiajs/react';

export default function Sekretaris() {
  return (
    <>
      <Head title="Sekretaris Kami" />
      <MainLayout>
        <Heading img="/images/100101.png" />
        <section className="pt-20 pb-10 lg:pt-[120px] lg:pb-20">
          <div className="container mx-auto">
            <KepengurusanHeading jobdesk="Sekretaris Kami" />
            <div className="mx-4 flex flex-wrap justify-center gap-20">
              {kepengurusan.map((pengurus) => (
                <KepengurusanCard key={pengurus.id} pengurus={pengurus} />
              ))}
            </div>
          </div>
        </section>
      </MainLayout>
    </>
  );
}

// resources/js/Pages/Kepengurusan/Sekretaris.vue
<template>

  <Loading v-if="isLoading" />

  <Head title="Sekretaris - Kepengurusan" />
  <Main :user="props.user">
    <Heading img="https://comit-unipi.vercel.app/_next/image?url=%2Farduino.png&w=1920&q=75" />
    <section class="pt-20 lg:pt-[120px] pb-10 lg:pb-20">
      <div class="container mx-auto">
        <KepengurusanHeading jobdesk="Sekretaris Kami" />
        <div class="flex flex-wrap gap-20 justify-center mx-4">
          <KepengurusanCard v-for="pengurus in kepengurusan" :key="pengurus.id" :pengurus="pengurus" />
        </div>
      </div>
    </section>
  </Main>
</template>

<script setup>
import Main from '@/Layouts/Main.vue';
import Loading from '@/components/Loading.vue';
import Heading from '@/components/ui/Heading.vue';
import KepengurusanCard from '@/components/ui/KepengurusanCard.vue';
import KepengurusanHeading from '@/components/ui/KepengurusanHeading.vue';

import { Head } from '@inertiajs/vue3';
import { useLoading } from '@/hooks/useLoading';
const { isLoading } = useLoading();

const props = defineProps({
  user: Object,
});
</script>

<script>
export default {
  data() {
    return {
      kepengurusan: [
        {
          id: 1,
          img: "/images/kepengurusan-2024-2025/sekretaris-1.jpg",
          nama: "Miftah Fadhillah",
          job: "Sekretaris 1",
        },
        {
          id: 2,
          img: "/images/kepengurusan-2024-2025/sekretaris-2.jpg",
          nama: "Revalia Nur Rahmat",
          job: "Sekretaris 2",
        },
      ]
    };
  }
}
</script>
