// resources/js/Pages/Kepengurusan/Prasarana.vue
<template>

  <Loading v-if="isLoading" />

  <Head title="Prasarana COMIT">
    <link rel="icon" href="/images/logo_black.png" />
    <meta name="description" content="Kepengurusan COMIT 2024-2025 (Sahitya Arsa).">
  </Head>

  <Main :user="props.user">
    <Heading img="/images/100101.png" />
    <section class="pt-20 lg:pt-[120px] pb-10 lg:pb-20">
      <div class="container mx-auto">
        <KepengurusanHeading jobdesk="Prasarana Kami" />
        <div class="flex flex-wrap gap-20 justify-center mx-4">
          <KepengurusanCard v-for="pengurus in kepengurusan" :key="pengurus.id" :pengurus="pengurus" />
        </div>
      </div>
    </section>
  </Main>
</template>

<script setup>
import Main from '@/Layouts/Main.vue';
import Loading from '@/components/Loading.vue';
import Heading from '@/components/ui/Heading.vue';
import KepengurusanCard from '@/components/ui/KepengurusanCard.vue';
import KepengurusanHeading from '@/components/ui/KepengurusanHeading.vue';

import { Head } from '@inertiajs/vue3';
import { useLoading } from '@/hooks/useLoading';
import { kepengurusan } from '@/data/kepengurusan/prasarana.js';

const { isLoading } = useLoading();

const props = defineProps({
  user: Object,
});
</script>

// resources/js/pages/Core/Kepengurusan/Prasarana.tsx
import KepengurusanCard from '@/components/core-card-kepengurusan';
import Heading from '@/components/core-heading';
import KepengurusanHeading from '@/components/core-heading-kepengurusan';
import { kepengurusan } from '@/constants/kepengurusan/prasarana';
import MainLayout from '@/layouts/main-layout';
import { Head } from '@inertiajs/react';

export default function Prasarana() {
  return (
    <>
      <Head title="Prasarana Kami Periode 2024-2025">
        <meta name="robots" content="index, follow" />
        <meta rel="canonical" content="https://comitunipi.com/kepengurusan/prasarana" />
        <meta name="description" content="Kenali prasarana COMIT periode 2024-2025" />

        <meta property="og:title" content="Prasarana Kami Periode 2024-2025 - COMIT UNIPI" />
        <meta property="og:description" content="Kenali prasarana COMIT periode 2024-2025" />
        <meta property="og:image" content="https://comitunipi.com/images/banner.png" />
        <meta property="og:image:width" content="1200" />
        <meta property="og:image:height" content="630" />
        <meta property="og:url" content="https://comitunipi.com/kepengurusan/prasarana" />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="COMIT UNIPI" />
        <meta property="og:locale" content="id_ID" />

        <script type="application/ld+json">
          {JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'WebPage',
            name: 'Prasarana Kami Periode 2024-2025 - COMIT UNIPI',
            url: 'https://comitunipi.com/kepengurusan/prasarana',
            mainEntity: {
              '@type': 'ItemList',
              itemListElement: kepengurusan.map((pengurus, index) => ({
                '@type': 'ListItem',
                position: index + 1,
                item: {
                  '@type': 'Person',
                  name: pengurus.nama,
                  jobTitle: pengurus.job,
                  image: `https://comitunipi.com${pengurus.img}`,
                  memberOf: {
                    '@type': 'Organization',
                    name: 'COMIT UNIPI',
                    url: 'https://comitunipi.com/',
                  },
                },
              })),
            },
            sameAs: ['https://www.instagram.com/comit.ipem/', 'https://www.tiktok.com/@comit_unipi', 'https://github.com/comitUnipi'],
          })}
        </script>
      </Head>
      <MainLayout>
        <Heading img="/images/100101.png" />
        <section className="pt-20 pb-10 lg:pt-[120px] lg:pb-20">
          <div className="container mx-auto">
            <KepengurusanHeading jobdesk="Prasarana Kami" />
            <div className="mx-4 flex flex-wrap justify-center gap-20">
              {kepengurusan.map((pengurus) => (
                <KepengurusanCard key={pengurus.id} pengurus={pengurus} />
              ))}
            </div>
          </div>
        </section>
      </MainLayout>
    </>
  );
}
