// resources/js/Pages/MentorKami.vue
<template>

  <Loading v-if="isLoading" />

  <Head title="Mentor COMIT">
    <link rel="icon" href="/images/logo_black.png" />
    <meta name="description"
      content="Kami mempunyai beberapa mentor yang sudah berpengalaman di bidangnya masing-masing.">
  </Head>

  <Main :user="props.user">
    <Heading img="/images/100102.png" />
    <Mentor />
  </Main>
</template>

<script setup>
import Main from '@/Layouts/Main.vue';
import Mentor from '@/components/Mentor.vue';
import Loading from '@/components/Loading.vue';
import Heading from '@/components/ui/Heading.vue';

import { Head } from '@inertiajs/vue3';
import { useLoading } from '@/hooks/useLoading';
const { isLoading } = useLoading();

const props = defineProps({
  user: Object,
});
</script>

// resources/js/pages/MentorKami.tsx
import MentorCard from '@/components/core-card-mentor';
import Heading from '@/components/core-heading';
import SubHeading from '@/components/core-sub-heading';
import { mentors } from '@/constants/mentor';
import MainLayout from '@/layouts/main-layout';
import { Head } from '@inertiajs/react';

export default function MentorKami() {
  return (
    <>
      <Head title="Mentor Kami" />
      <MainLayout>
        <Heading img="/images/100111.png" />
        <section className="pt-20 pb-10 lg:pt-[120px] lg:pb-20 dark:bg-white">
          <div className="container mx-auto">
            <SubHeading
              subtitle="Mentor"
              title="Perkenalkan Mentor Kami"
              description="Kami mempunyai beberapa mentor yang sudah berpengalaman di bidangnya masing-masing."
            />
            <div className="mx-4 flex flex-wrap justify-center">
              {mentors.map((mentor) => (
                <MentorCard key={mentor.id} mentor={mentor} />
              ))}
            </div>
          </div>
        </section>
      </MainLayout>
    </>
  );
}
