// resources/js/components/Loading.vue
<template>
  <div class="loading-overlay">
    <div class="spinner"></div>
    <img src="/images/logo_black.png" alt="Logo" class="spinner-logo" />
  </div>
</template>

<style scoped>
.loading-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(255, 255, 255, 1);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 9999;
}

.spinner {
  position: absolute;
  border: 4px solid rgba(255, 255, 255, 0.3);
  border-top: 4px solid #3498db;
  border-radius: 50%;
  width: 250px;
  height: 250px;
  animation: spin 1s linear infinite;
}

.spinner-logo {
  position: absolute;
  width: 150px;
  height: 150px;
  z-index: 10;
  pointer-events: none;
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }

  100% {
    transform: rotate(360deg);
  }
}
</style>

// resources/js/components/loading.tsx
export default function Loading() {
  return (
    <div className="fixed top-0 left-0 z-[9999] flex h-full w-full items-center justify-center bg-white">
      <div className="absolute h-[250px] w-[250px] animate-spin rounded-full border-4 border-white/30 border-t-[#3498db]"></div>
      <img src="/images/logo/logo_black.png" alt=" " className="pointer-events-none absolute z-10 h-[150px] w-[150px]" />
    </div>
  );
}
